CREATE TABLE FEE_STUDENT 
  (ROLLNO VARCHAR(45), 
	NAME VARCHAR(45), 
	EMAIL VARCHAR(45), 
	SEX VARCHAR(45), 
	COURSE VARCHAR(45), 
	FEE DECIMAL, 
	PAID DECIMAL, 
	DUE DECIMAL, 
	ADDRESS VARCHAR(45), 
	CONTACT VARCHAR(45), 
	 CONSTRAINT FEE_STUDENT_PK PRIMARY KEY (ROLLNO) 
  );

CREATE TABLE FEE_ACCOUNTANT 
  (	ID INT, 
	NAME VARCHAR(45), 
	EMAIL VARCHAR(45), 
	PASSWORD VARCHAR(45), 
	ADDRESS VARCHAR(45), 
	CONTACT VARCHAR(45), 
	 CONSTRAINT FEE_ACCOUNTANT_PK PRIMARY KEY (ID) 
  );