CREATE TABLE  COMPANY_MAILER_USER(	ID INT, 
	NAME VARCHAR(45), 
	EMAIL VARCHAR(45), 
	PASSWORD VARCHAR(45), 
	GENDER VARCHAR(45), 
	DOB DATE, 
	ADDRESSLINE VARCHAR(45), 
	CITY VARCHAR(45), 
	STATE VARCHAR(45), 
	COUNTRY VARCHAR(45), 
	CONTACT VARCHAR(45), 
	REGISTEREDDATE DATE, 
	AUTHORIZED VARCHAR(45), 
	 CONSTRAINT COMPANY_MAILER_USER_PK PRIMARY KEY (ID) 
   );
/

CREATE TABLE  COMPANY_MAILER_MESSAGE
   (	ID 	int, 
	SENDER VARCHAR(45), 
	RECEIVER VARCHAR(45), 
	SUBJECT VARCHAR(45), 
	MESSAGE VARCHAR(45), 
	TRASH VARCHAR(45), 
	MESSAGEDATE DATE, 
	 CONSTRAINT COMPANY_MAILER_MESSAGE_PK PRIMARY KEY (ID) 
   );
/