CREATE TABLE E_BOOK 
  (	CALLNO VARCHAR(45), 
	NAME VARCHAR(45), 
	AUTHOR VARCHAR(45), 
	PUBLISHER VARCHAR(45), 
	QUANTITY int, 
	ISSUED int, 
	 CONSTRAINT E_BOOK_PK PRIMARY KEY (CALLNO) 
  );
/
CREATE TABLE E_LIBRARIAN 
  (	ID int, 
	NAME VARCHAR(45), 
	PASSWORD VARCHAR(45), 
	EMAIL VARCHAR(45), 
	MOBILE int, 
	 CONSTRAINT E_LIBRARIAN_PK PRIMARY KEY (ID) 
  );
/
Note: ID must be generated through sequence in E_LIBRARIAN table.

CREATE TABLE E_ISSUEBOOK 
  (	CALLNO VARCHAR(45) NOT NULL , 
	STUDENTID VARCHAR(45) NOT NULL , 
	STUDENTNAME VARCHAR(45), 
	STUDENTMOBILE int, 
	ISSUEDDATE DATE, 
	RETURNSTATUS VARCHAR(45)
  );
/


